name: 'Telepresence Intercept'
description: 'Intercepts a service in a remote cluster'
inputs:
  telepresence_api_key:
    description: API KEY to login in app.getambassador.io
    required: true
  service_name:
    description: The name of the ervice to intercept
    required: true
  service_port:
    description: The port to intercept
    required: true
  kubeconfig_file:
    description: Content of the  kubernetes configuration used with kubectl
    required: true
  namespace:
    description: The namespace of the service to intercept
    required: false
    default: default
  http_header:
    description: Only intercept traffic that matches this "HTTP2_HEADER=REGEXP" specifier
    required: false
    default: "x-telepresence-intercept-id=service-intercepted"
  version:
    description: The version  of Telepresence to use
    required: false
    default: latest
runs:
  using: "composite"
  steps:
    - name: Checkout local
      uses: actions/checkout@v3
    - name: Install Telepresence
      uses: ./install/
      with:
        version: ${{ inputs.version }}
    - name: Create kubeconfig file
      shell: bash
      run: |
        cat <<EOF > /opt/kubeconfig
        ${{ inputs.kubeconfig_file }}
        EOF
        echo "KUBECONFIG=/opt/kubeconfig" >> $GITHUB_ENV
    - name: Connect Telepresence
      shell: bash
      run: telepresence login --apikey=${{inputs.telepresence_api_key}}
    - name: Intercept the service
      shell: bash
      run: telepresence intercept ${{inputs.service_name}} --port ${{inputs.service_port}} --ingress-host ambassador.ambassador --ingress-port 80 --ingress-tls --ingress-l5 ambassador.ambassador -n ${{inputs.namespace}} --http-header=${{inputs.http_header}}

