name: 'Telepresence Install'
description: 'Installs an specific version of telepresence'
inputs:
  version:
    description: Version of Telepresence to Install
    required: false
    default: latest
runs:
  using: 'node16'
  pre: 'dist/preinstall/index.js'
  main: 'dist/install/index.js'
