name: 'Configure Telepresence on the repository'
description: 'Set the configuration to use telepresence in the repository'
inputs:
  version:
    description: The version of telepresence to use
    required: false
    default: latest
runs:
  using: 'node16'
  main: 'dist/configure/index.js'
